// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ClimeiMvc.Data;

#nullable disable

namespace ClimeiMvc.Migrations
{
    [DbContext(typeof(climei_mvcContext))]
    [Migration("20231122140128_Initial9")]
    partial class Initial9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClimeiMvc.Models.DadosUsuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("Altura")
                        .HasColumnType("float");

                    b.Property<double>("Peso")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId")
                        .IsUnique();

                    b.ToTable("DadosUsuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogAgua", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogAgua");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogBatimentoOxigenacao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<double>("Quantidade")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogBatimentoOxigenacao");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogTemperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelTemperaturaId")
                        .HasColumnType("int");

                    b.Property<double>("Temperatura")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelTemperaturaId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogTemperatura");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogUmidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("NivelUmidadeId")
                        .HasColumnType("int");

                    b.Property<double>("Umidade")
                        .HasColumnType("float");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NivelUmidadeId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("LogUmidade");
                });

            modelBuilder.Entity("ClimeiMvc.Models.NivelTemperatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelTemperatura");
                });

            modelBuilder.Entity("ClimeiMvc.Models.NivelUmidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateAvaliacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Faixa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NivelUmidade");
                });

            modelBuilder.Entity("ClimeiMvc.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Idade")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.DadosUsuario", b =>
                {
                    b.HasOne("ClimeiMvc.Models.Usuario", "Usuario")
                        .WithOne("DadosUsuario")
                        .HasForeignKey("ClimeiMvc.Models.DadosUsuario", "UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogAgua", b =>
                {
                    b.HasOne("ClimeiMvc.Models.Usuario", "Usuario")
                        .WithMany("LogAgua")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogBatimentoOxigenacao", b =>
                {
                    b.HasOne("ClimeiMvc.Models.Usuario", "Usuario")
                        .WithMany("LogBatimentoOxigenacao")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogTemperatura", b =>
                {
                    b.HasOne("ClimeiMvc.Models.NivelTemperatura", "NivelTemperatura")
                        .WithMany("LogTemperatura")
                        .HasForeignKey("NivelTemperaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimeiMvc.Models.Usuario", "Usuario")
                        .WithMany("LogTemperatura")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelTemperatura");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.LogUmidade", b =>
                {
                    b.HasOne("ClimeiMvc.Models.NivelUmidade", "NivelUmidade")
                        .WithMany("LogUmidade")
                        .HasForeignKey("NivelUmidadeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClimeiMvc.Models.Usuario", "Usuario")
                        .WithMany("LogUmidade")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NivelUmidade");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ClimeiMvc.Models.NivelTemperatura", b =>
                {
                    b.Navigation("LogTemperatura");
                });

            modelBuilder.Entity("ClimeiMvc.Models.NivelUmidade", b =>
                {
                    b.Navigation("LogUmidade");
                });

            modelBuilder.Entity("ClimeiMvc.Models.Usuario", b =>
                {
                    b.Navigation("DadosUsuario")
                        .IsRequired();

                    b.Navigation("LogAgua");

                    b.Navigation("LogBatimentoOxigenacao");

                    b.Navigation("LogTemperatura");

                    b.Navigation("LogUmidade");
                });
#pragma warning restore 612, 618
        }
    }
}
